#ifndef NEXILISC_PROTOCOL_TYPE_C_H
#define NEXILISC_PROTOCOL_TYPE_C_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    PROTOCOL_TYPE_UNKNOWN,

    PROTOCOL_TYPE_AF_INET_UDP_SERVER,
    PROTOCOL_TYPE_AF_INET_UDP_CLIENT,
    PROTOCOL_TYPE_AF_INET_TCP_SERVER,
    PROTOCOL_TYPE_AF_INET_TCP_CLIENT,

    PROTOCOL_TYPE_BOOST_UDP_SERVER,
    PROTOCOL_TYPE_BOOST_UDP_CLIENT,
    PROTOCOL_TYPE_BOOST_TCP_SERVER,
    PROTOCOL_TYPE_BOOST_TCP_CLIENT,

    PROTOCOL_TYPE_AF_UNIX_SOCK_DGRAM_CLIENT,
    PROTOCOL_TYPE_AF_UNIX_SOCK_DGRAM_SERVER,
    PROTOCOL_TYPE_AF_UNIX_SOCK_STREAM_CLIENT,
    PROTOCOL_TYPE_AF_UNIX_SOCK_STREAM_SERVER
} nexilis_ProtocolTypeC;

#ifdef __cplusplus
}
#endif

#endif
