name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cpp-check:
    name: cppcheck
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get update && sudo apt-get install -y cppcheck expect

      - name: Run cppcheck.py
        run: |
          pip install -r scripts/requirements.txt
          python scripts/src/env.py
          python scripts/src/cppcheck.py

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          pip install -r scripts/requirements.txt
          python scripts/src/env.py
          python scripts/src/format.py

  cpp-tests:
    name: Run Native Tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -y \
          cmake \
          g++ \
          libgtest-dev \
          libboost-json-dev \

      - name: Install Nexilis
        run: |
          cd nexilis
          rm -rf build install
          cmake -B build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/nexilis/build/install
          cmake --build build --target install -- -j${nproc}

      - name: Build and run tests
        run: |
          cd tests/nexilis
          rm -rf build
          mkdir build && cd build
          cmake .. -DNEXILIS_IS_CI=1
          cmake --build .
          ./nexilis_tests

  c-tests:
    name: Run nexilisc Tests
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Update submodules
        run: git submodule sync --recursive && git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -y cmake gcc libgtest-dev libboost-all-dev

      - name: Build and run C tests
        run: |
          cd tests/nexilisc
          rm -rf build
          mkdir build
          cd build
          cmake ..
          make
          ./nexilis_c_tests

  alias-check:
    name: Check Correct Alias Usage
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run best_practices.py
        run: |
          pip install -r scripts/requirements.txt
          python scripts/src/env.py

          output=$(python scripts/src/best_practises.py)
          if [ "$output" = "0" ]; then
            echo "Best practices successful."
          else
            exit 1
          fi
